image: Visual Studio 2017
environment:
    url_boost_7z_file: https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.7z
    url_sdl_zip_file: https://www.libsdl.org/release/SDL-devel-1.2.15-VC.zip
install:
    - ps: >-
        Invoke-WebRequest ${env:url_boost_7z_file} -OutFile ${env:APPVEYOR_BUILD_FOLDER}/boost.7z

        Invoke-WebRequest ${env:url_sdl_zip_file} -OutFile ${env:APPVEYOR_BUILD_FOLDER}/sdl.zip

    - cmd: >-
        7z x %APPVEYOR_BUILD_FOLDER%\boost.7z boost_1_68_0\boost -y -o"%APPVEYOR_BUILD_FOLDER%\ext\" >NUL

        move "%APPVEYOR_BUILD_FOLDER%\ext\boost_1_68_0\boost" "%APPVEYOR_BUILD_FOLDER%\ext\include\boost"

        7z x %APPVEYOR_BUILD_FOLDER%\sdl.zip SDL-1.2.15\include -y -o"%APPVEYOR_BUILD_FOLDER%\ext\" >NUL

        move "%APPVEYOR_BUILD_FOLDER%\ext\SDL-1.2.15\include" "%APPVEYOR_BUILD_FOLDER%\ext\include\SDL"

# artifacts:
  # - path: 
# deploy:
  # provider: GitHub
  # release: Debug Build b$(appveyor_build_version)
  # description: 'Debug Build b$(appveyor_build_version)'
  # auth_token:
    # secure: 89XROd4oa6+aGRM36tBcVtEOFXHyH7f8nH51GHrK0trN01/+m/Lgu0uCPK1LNkG4
  # draft: false
  # prerelease: false
  # on:
    # branch: master                # release from master branch only
    # appveyor_repo_tag: true       # deploy on tag push only
