image: Visual Studio 2017
install:
  - TREE /F C:\ > tree.txt

artifacts:
  - path: tree.txt
# deploy:
  # provider: GitHub
  # release: Debug Build b$(appveyor_build_version)
  # description: 'Debug Build b$(appveyor_build_version)'
  # auth_token:
    # secure: 89XROd4oa6+aGRM36tBcVtEOFXHyH7f8nH51GHrK0trN01/+m/Lgu0uCPK1LNkG4
  # draft: false
  # prerelease: false
  # on:
    # branch: master                # release from master branch only
    # appveyor_repo_tag: true       # deploy on tag push only
